title: ChinaComx
description: Comics Culture in the People's Republic of China
url: "http://127.0.0.1:4000"
baseurl: ""
theme: minima

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: false
      show_date: true
      comments: true
      share: true
      related: true

# Pagination settings
paginate: 3
paginate_path: "/page:num/"
